### ISSUE TITLE
feature读取时的问题

### ISSUE THREAD

**Issue by Xue-Yw** [WENGSYX/MutualSL#3]
有一部分feature读取会报错，cannot reshape array of size 554117 into shape (743,1024)
![image](https://github.com/WENGSYX/MutualSL/assets/56827857/7bf5686a-be48-4d2f-a136-520b6672a623)

**Comment by WENGSYX** [comment]
建议跳过这部分feature，使用try

**Comment by Xue-Yw** [comment]
> 建议跳过这部分feature，使用try

谢谢，已解决
